name = "Maverick"
license = "MIT"
licenselink = "https://github.com/canhtran/maverick/blob/main/LICENSE"
description = "A mimimal hugo theme focuses on content"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Tran Duy Canh, Calvin"
  homepage = ""

# If porting an existing theme
[original]
  name = "Ronalds Vilciņš"
  homepage = "https://ronaldsvilcins.com"
  repo = "https://github.com/ronv/listed"
